-- RESET SCHEMA
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 1. Create Profiles (Linked to Supabase Auth)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text UNIQUE NOT NULL,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone DEFAULT now()
);

-- 2. Create Items (Inventory)
CREATE TABLE public.items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  unit text NOT NULL DEFAULT 'kg',
  quantity decimal(10, 2) NOT NULL DEFAULT 0,
  reorder_level decimal(10, 2) NOT NULL DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quantity_check CHECK (quantity >= 0)
);

-- 3. Create Transactions (Historical Logs)
CREATE TABLE public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint REFERENCES public.items(id) ON DELETE SET NULL,
  item_name text NOT NULL, -- Snapshot for history
  type text NOT NULL CHECK (type IN ('RESTOCK', 'WITHDRAWAL')),
  quantity decimal(10, 2) NOT NULL,
  unit text NOT NULL,
  person text NOT NULL, -- Email of authenticated user
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- ENABLE RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- POLICIES (Allow authenticated users only)
CREATE POLICY "Authenticated users can view profiles" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can manage inventory" ON public.items FOR ALL TO authenticated USING (true);
ALTER TABLE public.items ADD CONSTRAINT stock_not_negative CHECK (quantity >= 0);

-- ATOMIC TRANSACTION FUNCTION (Prevent Crashes & Corruption)
-- This ensures stock adjustment and logging happen as ONE single action.
CREATE OR REPLACE FUNCTION process_stock_transaction(
  p_item_id BIGINT,
  p_qty NUMERIC,
  p_type TEXT,
  p_person TEXT,
  p_notes TEXT DEFAULT ''
) RETURNS void AS $$
DECLARE
  v_item_name TEXT;
  v_item_unit TEXT;
BEGIN
  -- 1. Get and Lock item for update (prevents race conditions)
  SELECT name, unit INTO v_item_name, v_item_unit FROM public.items WHERE id = p_item_id FOR UPDATE;
  
  -- 2. Update stock based on type
  IF p_type = 'RESTOCK' THEN
    UPDATE public.items SET quantity = quantity + p_qty WHERE id = p_item_id;
  ELSIF p_type = 'WITHDRAWAL' THEN
    UPDATE public.items SET quantity = quantity - p_qty WHERE id = p_item_id;
  END IF;

  -- 3. Log the transaction
  INSERT INTO public.transactions (item_id, item_name, type, quantity, unit, person, notes)
  VALUES (p_item_id, v_item_name, p_type, p_qty, v_item_unit, p_person, p_notes);

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE POLICY "Authenticated users can manage transactions" ON public.transactions FOR ALL TO authenticated USING (true);

-- AUTO-CREATE PROFILE ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
